- name: Backup Router and Switch Configs
  hosts: all
  gather_facts: no

  tasks:
    - name: Get running config
      cisco.ios.ios_command:
        commands:
          - show running-config
      register: config

    - name: Save config locally
      copy:
        content: "{{ config.stdout[0] }}"
        dest: "backups/{{ inventory_hostname }}-config.txt"
