# playbooks/router_enable_test.yml
---
- name: Router enable-mode test (forced enable)
  hosts: R1
  gather_facts: no
  connection: network_cli
  become: true
  become_method: enable

  tasks:
    - name: Show hostname from running-config
      cisco.ios.ios_command:
        commands:
          - show running-config | section hostname
      register: out

    - debug:
        var: out.stdout_lines
