- name: Shutdown unused switch ports
  hosts: switches
  gather_facts: no

  tasks:
    - name: Disable unused access ports
      cisco.ios.ios_config:
        parents: interface range FastEthernet0/10 - 24
        lines:
          - description UNUSED - SHUTDOWN
          - shutdown

